name: deploy-cloud-resume

on:
    workflow_dispatch: 

permissions:
  id-token: write
  contents: read
jobs:
    deploy-cloud:
        name: "Deploy Cloud Resume Challenge"
        runs-on: ubuntu-latest
        environment: testing
        steps:
              
            - name: "Check repository files"
              uses: actions/checkout@v4

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v1
              with:
                terraform_version: '1.4.0'

            - name: "Configure AWS Creds"
              uses: aws-actions/configure-aws-credentials@v4.1.0
              with:
                aws-region: ${{ secrets.AWS_REGION }}
                role-to-assume: ${{ secrets.IAM_ARN }}
                role-session-name: samplerolesession

            - name: "Terraform init"
              run: terraform init

            - name: "Terraform plan"
              run: terraform plan

            # - name: "Run Powershell script"
            #   shell: pwsh
            #   run: |
            #     . .\Deploy-CloudResume.ps1
            #     Deploy_Cloud -action apply -verbose
              